apiVersion: apps/v1
kind: Deployment
metadata:
  name: curupira-mcp-server
  labels:
    app: curupira
    component: mcp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curupira
      component: mcp-server
  template:
    metadata:
      labels:
        app: curupira
        component: mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: curupira
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: mcp-server
        image: drzzln/curupira:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: CURUPIRA_TRANSPORT
          value: "sse"
        - name: CURUPIRA_PORT
          value: "3000"
        - name: CURUPIRA_CDP_HOST
          value: "chrome-headless.shared-services.svc.cluster.local"
        - name: CURUPIRA_CDP_PORT
          value: "3000"
        - name: CURUPIRA_LOG_LEVEL
          value: "info"
        - name: CURUPIRA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: curupira-secrets
              key: jwt-secret
        - name: CURUPIRA_JWT_ISSUER
          value: "curupira.nexus.io"
        - name: CURUPIRA_JWT_AUDIENCE
          value: "curupira-mcp"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - curupira
              topologyKey: kubernetes.io/hostname