apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: curupira

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: curupira
  version: v1.1.3

images:
  - name: drzzln/curupira
    newTag: 1.1.3