apiVersion: v1
kind: Secret
metadata:
  name: curupira-secrets
  labels:
    app: curupira
    component: mcp-server
type: Opaque
stringData:
  # JWT secret for authentication (replace with actual secret)
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  
  # Optional: JWT public key for RS256 (if using asymmetric signing)
  # jwt-public-key: |
  #   -----BEGIN PUBLIC KEY-----
  #   YOUR_PUBLIC_KEY_HERE
  #   -----END PUBLIC KEY-----