apiVersion: v1
kind: Service
metadata:
  name: curupira-mcp-server
  labels:
    app: curupira
    component: mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: curupira
    component: mcp-server
---
apiVersion: v1
kind: Service
metadata:
  name: curupira-mcp-server-headless
  labels:
    app: curupira
    component: mcp-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: curupira
    component: mcp-server