# Curupira MCP Server - Base Configuration
# Following Nexus Configuration Standards

version: "1.0"

server:
  name: "curupira-mcp-server"
  version: "1.1.3"
  host: "localhost"
  port: 8080
  environment: "development"

logging:
  level: "info"
  pretty: true
  format: "json"

transports:
  websocket:
    enabled: true
    path: "/mcp"
    pingInterval: 30000
    pongTimeout: 5000
  
  http:
    enabled: true
    path: "/mcp"
    timeout: 30000
  
  sse:
    enabled: true
    path: "/mcp/sse"
    keepAliveInterval: 30000

healthCheck:
  enabled: true
  path: "/health"
  interval: 30000

cors:
  origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
  credentials: true

rateLimit:
  enabled: true
  max: 100
  window: 60000

auth:
  enabled: false
  jwtSecret: "development-secret"
  tokenExpiry: "24h"

chrome:
  enabled: true
  serviceUrl: "http://localhost:9222"
  connectTimeout: 5000
  pageTimeout: 30000
  defaultViewport:
    width: 1920
    height: 1080
  
  discovery:
    enabled: true
    hosts:
      - "localhost"
      - "127.0.0.1"
    ports:
      - 9222
      - 9223
      - 9224
      - 9225
      - 9226
    timeout: 5000
    autoConnect: false
    preferredPatterns:
      - "localhost"
      - "react"
      - "vite"
      - "next"
      - "webpack"
      - "development"
      - "dev"

performance:
  maxMessageSize: 10485760  # 10MB
  debounceMs: 100
  throttleMs: 1000

resources:
  maxConsoleLogEntries: 1000
  maxNetworkRequests: 500
  cacheSize: 100